### PR TITLE
fix: adding Hardhat Dockerfile in GitHub Workflow

### LINKED ISSUE #692: Missing Hardhat Dockerfile in GitHub Workflow
## Description  
The `docker-compose` file for Studio includes a Hardhat service that uses a custom Dockerfile. However, this custom Dockerfile is not currently part of our GitHub workflow. Consequently, the following issues arise:  
- Hardhat images are not being published to the Docker registry.  
- These images are not available for the CLI.

### PR DESCRIPTION
**Pull request by epsjunior**
Fixes #692 

# What

- Added a `hardhat` step to the GitHub workflow to build and push a Docker image for the Hardhat service.
- Configured the step to use the `docker-build-and-push-image.yml` reusable workflow with appropriate parameters:
  - `docker_build_context`: `.`
  - `dockerfile`: `docker/Dockerfile.hardhat`
  - `dockerhub_repo`: `yeagerai/simulator-hardhat`
  - `dockerhub_username`: `${{ vars.DOCKERHUB_USERNAME }}`
  - `dockerhub_token`: `${{ secrets.DOCKERHUB_TOKEN }}`

# Why

- To address the issue of missing Hardhat Docker images in the registry.
- To ensure the Hardhat service is available for CLI and dependent services, aligning it with other Studio services.

# Testing done

- Verified workflow syntax locally.
- Confirmed similar jobs for other services (e.g., `jsonrpc`, `frontend`) function as expected using the reusable workflow.

# Decisions made

- Used the existing reusable workflow for consistency across services.
- Chose not to add additional Dockerfile-specific testing in this PR, as the reusable workflow already ensures proper image building.

# Checks

- [x] I have tested this code.
- [x] I have reviewed my own PR.
- [x] I have created an issue for this PR.
- [x] I have set a descriptive PR title compliant with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

# Reviewing tips

- Focus on the added `hardhat` step in the workflow and confirm the parameters are correct.
- Check the reusable workflow configuration for consistency with other services.

# User facing release notes

- Added a Hardhat Docker image to the CI/CD workflow. The image is now published to Docker Hub, making it available for use in Studio and CLI-related services.

### CODE REVIEW

**Review by AgustinRamiroDiaz — APPROVED** [review]
for another PR:
We should also re-think the names for the images, since we are renaming from `simulator`. Maybe `localnetwork` or `studio`

cc @cristiam86 @MuncleUscles  what's the branding here?

**Comment by cristiam86** [comment]
Studio is the whole product. Local net is the backend which can be used on its own

**Comment by AgustinRamiroDiaz** [comment]
> Studio is the whole product. Local net is the backend which can be used on its own

@cristiam86 so do you think the images should be `studio-frontend` and then `localnetwork-image-name` for all the rest?

**Comment by cristiam86** [comment]
> > Studio is the whole product. Local net is the backend which can be used on its own
> 
> 
> 
> @cristiam86 so do you think the images should be `studio-frontend` and then `localnetwork-image-name` for all the rest?

Makes sense, not sure it should be done on this PR though.

**Comment by cristiam86** [comment]
@epsjunior we just merged this PR, which had failing tests. This is no longer allowed unless we manually take a look and discuss the issue that is making the tests fail. 
The issue seems to be building the frontend, which was addressed in the last PR. I wonder if this is due to not having the branch updated with main before merging

**Comment by epsjunior** [comment]
> @epsjunior we just merged this PR, which had failing tests. This is no longer allowed unless we manually take a look and discuss the issue that is making the tests fail. The issue seems to be building the frontend, which was addressed in the last PR. I wonder if this is due to not having the branch updated with main before merging

Ok, got it

And yes, the branch wasn't updated with main, because of that some tests failed

**Pull request merged**
